image: archlinux
packages:
  - lowdown
  - cpio
oauth: pages.sr.ht/PAGES:RW
environment:
  site: wculhane.com
tasks:
- package: |
    cd $site
    make site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site \
    -Fcontent=@$site/site.tar.gz
